name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
  
categories:
 - title: 'Features'
   label: 'enhancement'
 - title: 'Bug Fixes'
   label: 'bug'
   
exclude-labels:
 - 'skip'
 
autolabeler:
  - label: 'bug'
    title:
      - '.*\[fix\].*'
  - label: 'enhancement'
    title:
      - '.*feat.*'
  - label: 'skip'
    title:
      - '.*\[skip\].*'
      
replacers:
  - search: '/\[feat\]/g'
    replace: 'toutafé'
  - search: '.*(\[feat\]).*'
    replace: ''
  - search: '.*(\[skip\]).*'
    replace: ''

template: |
  # What's Changed
  
  $CHANGES
