name: CD prod

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      REALEASE_TAG: ${{ github.event.release.tag_name || github.event.inputs.tag }}

    steps:
      - name: "deploy release"
        run: echo Deploy version ${{ REALEASE_TAG }} in production!
