name: CD prod

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${GITHUB_REF##*/}

    steps:
      - name: "deploy fresh release"
        run: echo Deploy version ${{ env.GITHUB_REF }} in production!
