name: CD prod

on:
  workflow_run:
    workflows: ["Release version"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${GITHUB_REF##*/}

    steps:
      - name: "deploy fresh release"
        run: echo Deploy version ${{ github.event.workflow_run.outputs }} in production!
