name: CD prod

on:   
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "deploy fresh release"
        run: echo Deploy version ${{ github.event.inputs.tag }} in production!
