name: CD prod

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:              
      - name: "set env"
        if: ${{ github.event.release }}
        run: echo ::set-env name=RELEASE_TAG::${{ github.event.release.tag_name }}
        
      - name: "set env"
        if: ${{ github.event.inputs.tag }}
        run: echo ::set-env name=RELEASE_TAG::${{ github.event.inputs.tag }}
        
      - name: "deploy release"
        run: echo Deploy version ${{ RELEASE_TAG }} in production!

