name: CD prod

on:
  release:
    types: [released]
    
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${GITHUB_REF##*/}

    steps:
      - name: "deploy fresh release"
        run: echo Deploy version ${{ github.event.release.name }} in production!
