name: CD prod

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${GITHUB_REF##*/}

    steps:
      - name: "deploy fresh release"
        run: echo Deploy version ${{ env.GITHUB_REF }} in production!
