name: CD prod

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "deploy release"

        if: ${{ github.event.release }}
        run: echo Deploy version ${{ github.event.release.tag_name }} in production!

      - name: "deploy release"
        if: ${{ github.event.inputs.tag }}
        run: echo Deploy version ${{ github.event.inputs.tag }} in production!
