name: CD Prod
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'

jobs:    
  printInputs:
    runs-on: ubuntu-latest
    steps:        
    - run: echo "::set-env name=INPUT_ALLOWED_FEATURES::${{ github.event.inputs.environment }}" 
      shell: bash 
    - run: |
        echo "Env: ${{ github.event.inputs.environment }}"
        echo "Branch: ${{ github.event.inputs.branch }}"
