name: Release version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump'
        required: true
        default: 'minor'

jobs:
  
  bump:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.bump }}
          RELEASE_BRANCHES: main
          
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.step1.outputs.tag }}
          prerelease: false
