name: Release version

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'env [staging/prod]'
        required: true
        default: 'staging'
      branch:
        description: 'branch'
        required: true
        default: 'master'
      version:
        description: 'tag'
        required: true

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - name: create tag from env value
        run: echo '::set-output name=TAG::${scripts/tag_name.sh ${{ github.event.inputs.version }}}'
        id: tag-name

      - name: Create tag
        uses: actions/github-script@v4
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ step.tag-name.outputs.TAG }}",
              sha: context.sha
            })
